from flask import Flask, request, jsonify
from rapidfuzz import process

app = Flask(__name__)

# Base de cursos e links
base_cursos = {
"Acompanhamento do Transtorno do Espectro Autista - TEA": "https://youtube.com/live/KPqiKY7KTMM",
"Administração": "https://www.youtube.com/watch?v=Y3wouylN9q0",
"Administração Pública": "https://www.youtube.com/watch?v=Y3wouylN9q0",
"Agrocomputação": "https://youtube.com/live/J8cTjwkezKc?feature=share",
"Agronomia": "https://youtube.com/live/Iloshe8q-ME?feature=share",
"Agrotecnologia": "https://youtube.com/live/J8cTjwkezKc?feature=share",
"Análise e Desenvolvimento de Sistemas": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Andragogia": "https://youtube.com/live/KPqiKY7KTMM",
"Antropologia": "https://youtube.com/live/JM_E4hw1Gko?feature=share",
"Arquitetura e Urbanismo": "https://youtube.com/live/fZry3g74iV4?feature=share",
"Arquivologia": "https://youtube.com/live/Hb_y6_C-g-E?feature=share",
"Artes Visuais": "https://youtube.com/live/tpxDF5s7duA?feature=share",
"Banco de Dados": "https://www.youtube.com/watch?v=k_svS5Pd0QU",
"Biblioteconomia": "https://youtube.com/live/Hb_y6_C-g-E?feature=share",
"Big Data e Inteligência Analítica": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Biomedicina": "https://youtube.com/live/bJpWLkZBUgM?feature=share",
"Ciência da Criatividade": "https://youtube.com/live/RrvSQ7-jAyc?feature=share",
"Ciência Política": "https://youtube.com/live/JM_E4hw1Gko?feature=share",
"Ciências Biológicas": "https://youtube.com/live/b6-lGaWSJaI?feature=share",
"Ciências Contábeis": "https://youtube.com/live/QH-VeGJyB_o?feature=share",
"Ciências da Religião": "https://youtube.com/live/4G-p66uG2Bw?feature=share",
"Ciências Econômicas": "https://youtube.com/live/J6WRIqbISsY?feature=share",
"Comércio Exterior": "https://youtube.com/live/luEFt4fMdbE?feature=share",
"Comunicação Institucional": "https://youtube.com/live/3vHWtOjARR8?feature=share",
"Construção de Edifícios": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Controle de Obras": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Criminologia": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Dança": "https://youtube.com/live/tpxDF5s7duA?feature=share",
"Defesa Médica Hospitalar": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Desenvolvimento de Aplicativos Móveis": "https://www.youtube.com/watch?v=k_svS5Pd0QU",
"Design de Animação": "https://youtube.com/live/OCe6NHHTFLU?feature=share",
"Design de Interiores": "https://youtube.com/live/OCe6NHHTFLU?feature=share",
"Design de Moda": "https://youtube.com/live/OCe6NHHTFLU?feature=share",
"Design de Produto": "https://youtube.com/live/OCe6NHHTFLU?feature=share",
"Design Digital e User Experience (UX)": "https://youtube.com/live/OCe6NHHTFLU?feature=share",
"Design Gráfico": "https://youtube.com/live/OCe6NHHTFLU?feature=share",
"Despachante Documentalista": "https://youtube.com/live/wVoF7sINd0E?feature=share",
"Educação Especial": "https://www.youtube.com/live/_dc6fHQU3DA",
"Educação Física - Bacharelado": "https://youtube.com/live/P35JhQAhM-w?feature=share",
"Educação Física - Licenciatura": "https://youtube.com/live/P35JhQAhM-w?feature=share",
"Educador Social": "https://youtube.com/live/Iellh2Yi6uk?feature=share",
"Energias Renováveis": "https://youtube.com/live/RfJnOvS-eCE?feature=share",
"Enfermagem": "https://youtube.com/live/rfwebhQqWwc?feature=share",
"Engenharia Ambiental e Sanitária": "https://youtube.com/live/fZry3g74iV4?feature=share",
"Engenharia Civil": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Engenharia da Produção": "https://youtube.com/live/fZry3g74iV4?feature=share",
"Engenharia de Energia": "https://youtube.com/live/RfJnOvS-eCE?feature=share",
"Engenharia de Software": "https://www.youtube.com/watch?v=k_svS5Pd0QU",
"Engenharia Elétrica": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Engenharia Mecânica": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Escrita Criativa": "https://youtube.com/live/JMUijYOXLcY?feature=share",
"Estética e Imagem Pessoal": "https://youtube.com/live/FLGsKtzQzlc?feature=share",
"Eventos": "https://youtube.com/live/luEFt4fMdbE?feature=share",
"Farmácia": "https://youtube.com/live/sLhYsduR-i0?feature=share",
"Filosofia": "https://youtube.com/live/4G-p66uG2Bw?feature=share",
"Física": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Fisioterapia": "https://youtube.com/live/jTL2XsjKU1I?feature=share",
"Formação Pedagógica em Artes Visuais": "https://youtube.com/live/tpxDF5s7duA?feature=share",
"Formação Pedagógica em Ciências Biológicas": "https://youtube.com/live/b6-lGaWSJaI?feature=share",
"Formação Pedagógica em Educação Especial": "https://www.youtube.com/live/_dc6fHQU3DA",
"Formação Pedagógica em Educação Física": "https://youtube.com/live/P35JhQAhM-w?feature=share",
"Formação Pedagógica em Física": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Formação Pedagógica em Geografia": "https://www.youtube.com/watch?v=9tchBoN759g",
"Formação Pedagógica em História": "https://www.youtube.com/watch?v=9tchBoN759g",
"Formação Pedagógica em Letras - Inglês": "https://youtube.com/live/Kos-wuA2evQ?feature=share",
"Formação Pedagógica em Letras - Libras": "https://www.youtube.com/watch?v=zvM7LpWgN2A",
"Formação Pedagógica em Letras- Espanhol": "https://www.youtube.com/live/_dc6fHQU3DA",
"Formação Pedagógica em Letras - Português": "https://youtube.com/live/Kos-wuA2evQ?feature=share",
"Formação Pedagógica em Química": "https://youtube.com/live/toiPnEWw8Do?feature=share",
"Formação Pedagógica em Filosofia": "https://youtube.com/live/4G-p66uG2Bw?feature=share",
"Formação Pedagógica em Informática": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Formação Pedagógica em Matemática": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Formação Pedagógica em Sociologia": "https://youtube.com/live/JM_E4hw1Gko?feature=share",
"Fotografia": "https://youtube.com/live/3vHWtOjARR8?feature=share",
"Gastronomia": "https://youtube.com/live/RuRgV_XHAWc?feature=share",
"Geografia": "https://www.youtube.com/watch?v=9tchBoN759g",
"Geoprocessamento": "https://www.youtube.com/watch?v=m8QfZ64wi1Y",
"Gerontologia": "https://youtube.com/live/Iellh2Yi6uk?feature=share",
"Gestão Ambiental": "https://youtube.com/live/dOfhkmazrKo?feature=share",
"Gestão Comercial": "https://youtube.com/live/QzI-ZJoK9tE?feature=share",
"Gestão da Inovação": "https://youtube.com/live/QzI-ZJoK9tE?feature=share",
"Gestão da Produção Industrial": "https://youtube.com/live/RfJnOvS-eCE?feature=share",
"Gestão da Qualidade": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Gestão da Tecnologia da Informação": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Gestão Das Relações Eletrônicas": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Gestão de Cidades Inteligentes e Sustentáveis": "https://youtube.com/live/fZry3g74iV4?feature=share",
"Gestão de Cooperativas": "https://youtube.com/live/QzI-ZJoK9tE?feature=share",
"Gestão de Farmácia": "https://youtube.com/live/wVoF7sINd0E?feature=share",
"Gestão de Investimentos e Mercado Financeiro": "https://youtube.com/live/J6WRIqbISsY?feature=share",
"Gestão de Inventário Extrajudicial": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Gestão de Negócios": "https://youtube.com/live/QzI-ZJoK9tE?feature=share",
"Gestão de Processos Educacionais": "https://youtube.com/live/J6WRIqbISsY?feature=share",
"Gestão de Recursos Humanos": "https://www.youtube.com/watch?v=Y3wouylN9q0",
"Gestão de Resíduos de Serviços de Saúde": "https://youtube.com/live/RfJnOvS-eCE?feature=share",
"Gestão de Saúde Pública": "https://youtube.com/live/bJpWLkZBUgM?feature=share",
"Gestão de Segurança Privada": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Gestão de Serviços Jurídicos": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Gestão de Serviços Jurídicos, Notariais e de Registro": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Gestão de Startups": "https://youtube.com/live/QzI-ZJoK9tE?feature=share",
"Gestão de Turismo": "https://youtube.com/live/z54rOMGbskg?feature=share",
"Gestão do Agronegócio": "https://youtube.com/live/J8cTjwkezKc?feature=share",
"Gestão e Empreendedorismo": "https://youtube.com/live/QzI-ZJoK9tE?feature=share",
"Gestão Financeira": "https://youtube.com/live/J6WRIqbISsY?feature=share",
"Gestão Hospitalar": "https://youtube.com/live/pG_CUsLJW6E?feature=share",
"Gestão Portuária": "https://youtube.com/live/luEFt4fMdbE?feature=share",
"Gestão Pública": "https://www.youtube.com/watch?v=Y3wouylN9q0",
"História": "https://www.youtube.com/watch?v=9tchBoN759g",
"Hotelaria": "https://youtube.com/live/z54rOMGbskg?feature=share",
"Informática": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Instrumentação Cirúrgica": "https://youtube.com/live/rfwebhQqWwc?feature=share",
"Inteligência Artificial e Machine Learning": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Internet das Coisas": "https://www.youtube.com/watch?v=k_svS5Pd0QU",
"Investigação Forense e Perícia Criminal": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Jogos Digitais": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Jornalismo Digital": "https://youtube.com/live/3vHWtOjARR8?feature=share",
"Letras - Libras - Bacharelado": "https://www.youtube.com/watch?v=zvM7LpWgN2A",
"Letras - Libras - Licenciatura": "https://www.youtube.com/watch?v=zvM7LpWgN2A",
"Letras-Alemão": "https://www.youtube.com/live/_dc6fHQU3DA",
"Letras-Espanhol": "https://www.youtube.com/live/_dc6fHQU3DA",
"Letras-Inglês": "https://youtube.com/live/Kos-wuA2evQ?feature=share",
"Letras-Português": "https://youtube.com/live/Kos-wuA2evQ?feature=share",
"Logística": "https://youtube.com/live/luEFt4fMdbE?feature=share",
"Marketing": "https://youtube.com/live/K8-FElD-duM?feature=share",
"Marketing Digital": "https://youtube.com/live/K8-FElD-duM?feature=share",
"Matemática": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Mediação": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Mídias Digitais": "https://youtube.com/live/3vHWtOjARR8?feature=share",
"Museologia": "https://youtube.com/live/Hb_y6_C-g-E?feature=share",
"Música": "https://youtube.com/live/tpxDF5s7duA?feature=share",
"Negócios Digitais": "https://youtube.com/live/K8-FElD-duM?feature=share",
"Negócios Imobiliários": "https://youtube.com/live/J6WRIqbISsY?feature=share",
"Nutrição": "https://youtube.com/live/RuRgV_XHAWc?feature=share",
"Pedagogia": "https://youtube.com/live/uD0cXzg7_E8?feature=share",
"Podologia": "https://youtube.com/live/FLGsKtzQzlc?feature=share",
"Processos Gerenciais": "https://youtube.com/live/pQkqlC3j5wc?feature=share",
"Produção Cultural": "https://youtube.com/live/JMUijYOXLcY?feature=share",
"Produção de Cerveja": "https://youtube.com/live/RuRgV_XHAWc?feature=share",
"Psicomotricidade": "https://youtube.com/live/P35JhQAhM-w?feature=share",
"Psicopedagogia": "https://youtube.com/live/uD0cXzg7_E8?feature=share",
"Publicidade e Propaganda": "https://youtube.com/live/3vHWtOjARR8?feature=share",
"Qualidade de Vida na Contemporaneidade": "https://youtube.com/live/KPqiKY7KTMM",
"Química": "https://youtube.com/live/toiPnEWw8Do?feature=share",
"Radiologia": "https://youtube.com/live/pG_CUsLJW6E?feature=share",
"Redes de Computadores": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Relações Internacionais": "https://youtube.com/live/luEFt4fMdbE?feature=share",
"Relações Públicas": "https://youtube.com/live/3vHWtOjARR8?feature=share",
"Saneamento Ambiental": "https://youtube.com/live/RfJnOvS-eCE?feature=share",
"Secretariado": "https://youtube.com/live/wVoF7sINd0E?feature=share",
"Segunda Licenciatura em Artes Visuais": "https://youtube.com/live/tpxDF5s7duA?feature=share",
"Segunda Licenciatura em Ciências Biológicas": "https://youtube.com/live/b6-lGaWSJaI?feature=share",
"Segunda Licenciatura em Educação Especial": "https://www.youtube.com/live/_dc6fHQU3DA",
"Segunda Licenciatura em Filosofia": "https://youtube.com/live/4G-p66uG2Bw?feature=share",
"Segunda Licenciatura em Física": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Segunda Licenciatura em Geografia": "https://www.youtube.com/watch?v=9tchBoN759g",
"Segunda Licenciatura em História": "https://www.youtube.com/watch?v=9tchBoN759g",
"Segunda Licenciatura em Informática": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Segunda Licenciatura em Letras - Inglês": "https://youtube.com/live/Kos-wuA2evQ?feature=share",
"Segunda Licenciatura em Letras Libras": "https://www.youtube.com/watch?v=zvM7LpWgN2A",
"Segunda Licenciatura em Letras- Espanhol": "https://www.youtube.com/live/_dc6fHQU3DA",
"Segunda Licenciatura em Letras - Português": "https://youtube.com/live/Kos-wuA2evQ?feature=share",
"Segunda Licenciatura em Matemática": "https://youtube.com/live/5isCp07YBfw?feature=share",
"Segunda Licenciatura em Química": "https://youtube.com/live/toiPnEWw8Do?feature=share",
"Segunda Licenciatura em Sociologia": "https://youtube.com/live/JM_E4hw1Gko?feature=share",
"Segurança da Informação": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Segurança no Trabalho": "https://youtube.com/live/7t0_KkwvHy4?feature=share",
"Segurança Pública": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Serviço Social": "https://youtube.com/live/Iellh2Yi6uk?feature=share",
"Serviços Penais": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Serviços Previdenciários": "https://youtube.com/live/eGI1_tjetK4?feature=share",
"Sistemas da Informação": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Sistemas para Internet": "https://youtube.com/live/4Mo-bAMfB4w?feature=share",
"Sociologia": "https://youtube.com/live/JM_E4hw1Gko?feature=share",
"Teatro": "https://youtube.com/live/tpxDF5s7duA?feature=share",
"Técnicas para Acompanhamento Terapêutico": "https://youtube.com/live/RrvSQ7-jAyc?feature=share",
"Teologia": "https://youtube.com/live/RrvSQ7-jAyc?feature=share",
"Terapia Ocupacional": "https://youtube.com/live/jTL2XsjKU1I?feature=share",
"Terapias Integrativas e Complementares": "https://youtube.com/live/FLGsKtzQzlc?feature=share",
"Tradução": "https://youtube.com/live/RrvSQ7-jAyc?feature=share",
"Varejo Digital": "https://www.youtube.com/watch?v=Y3wouylN9q0"
}

@app.route('/obter-link', methods=['POST'])
def obter_link():
    dados = request.json
    curso_input = dados.get("curso")
    
    if not curso_input:
        return jsonify({
            "status": "Erro",
            "mensagem": "Nenhum curso foi enviado."
        })
    
    melhor_curso, score, _ = process.extractOne(curso_input, base_cursos.keys())
    
    if score > 80:  # Define um limite para considerar uma correspondência válida
        return jsonify({
            "status": "Encontrado",
            "mensagem": "Curso identificado.",
            "curso": melhor_curso,
            "link": base_cursos[melhor_curso]
        })
    else:
        return jsonify({
            "status": "Nao_encontrado",
            "mensagem": "Curso não identificado na base."
        })

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 11000))  
    app.run(debug=True, host='0.0.0.0', port=port)
